.TH bd 1 "30 March 2024" "execdir 3.0.0"
.SH NAME
bd - build directory
.SH SYNOPSIS
.B bd
.SH DESCRIPTION
Executes the build task associated with the directory.
.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
EXECFILE  File used to hold execdir configuration.
.SH SEE ALSO
ed(1), id(1), sd(1), st(1), td(1), xd(1)
.SH COPYRIGHT
Copyright 2024 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
