.TH id 1 "30 March 2024" "execdir 3.0.0"
.SH NAME
id - initialize directory
.SH SYNOPSIS
.B id
.SH DESCRIPTION
Adds the current directory to the execdir configuration file.
.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
EXECFILE  File used to hold execdir configuration.
.SH SEE ALSO
bd(1), ed(1), sd(1), st(1), td(1), xd(1)
.SH COPYRIGHT
Copyright 2024 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
