.TH xd 1 "30 March 2024" "markdir 3.0.0"
.SH NAME
xd - execute directory
.SH SYNOPSIS
.B xd [task]
.B
.SH DESCRIPTION
Executes the named task associated with the directory, or the default task if task is not specified.
.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
EXECFILE  File used to hold execdir configuration.
.SH SEE ALSO
bd(1), ed(1), id(1), sd(1), st(1), td(1)
.SH COPYRIGHT
Copyright 2024 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
