.TH cm 1 "16 January 2022" "markdir 2.0.0"
.SH NAME
cm - check mark file
.SH SYNOPSIS
.B cm
.B
.SH DESCRIPTION
Remove marks from the mark file that do not have a existing associated directory.
.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
MARKFILE  File used to map marks to directories and directories to tasks.
.SH SEE ALSO
am(1), bm(1), dm(1), em(1), gm(1), im(1), lm(1), sm(1), tm(1), xm(1)
.SH COPYRIGHT
Copyright 2022 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
