.TH dm 1 "16 January 2022" "markdir 2.0.0"
.SH NAME
dm - delete mark
.SH SYNOPSIS
.B dm
.I mark
.B
.SH DESCRIPTION
Deletes a mark from the mark file.

For example,

$ sm log

/var/log

$ dm log

$ sm log

log not found

.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
MARKFILE  File used to map marks to directories and directories to tasks.
.SH SEE ALSO
am(1), bm(1), cm(1), em(1), gm(1), im(1), lm(1), sm(1), tm(1), xm(1)
.SH COPYRIGHT
Copyright 2022 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
