.TH dm 1 "13 November 2016" "markdir 1.0.0"
.SH NAME
dm - delete mark
.SH SYNOPSIS
.B dm
.I mark
.B
.SH DESCRIPTION
Deletes a mark from the mark file.

For example,

$ sm log

/var/log

$ dm log

$ sm log

log not found

.SH AUTHOR
Written by Charles Pilon.
.SH FILES
~/marks
.SH SEE ALSO
am(1), cm(1), em(1), gm(1), im(1), lm(1), sm(1)
.SH COPYRIGHT
Copyright 2016 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
