.TH em 1 "17 January 2022" "markdir 2.1.0"
.SH NAME
em - edit mark file
.SH SYNOPSIS
.B em
.B
.SH DESCRIPTION
Edits the mark file using the editor specified in the EDITOR environment variable.
.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
MARKFILE  File used to map marks to directories and directories to tasks.
EDITOR    Executable used to edit the mark file.
.SH SEE ALSO
am(1), bd(1), cm(1), dm(1), gm(1), im(1), lm(1), sm(1), td(1), xd(1)
.SH COPYRIGHT
Copyright 2022 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
