.TH gm 1 "13 November 2016" "markdir 1.0.0"
.SH NAME
gm - goto mark
.SH SYNOPSIS
.B gm
.I mark
.B
.SH DESCRIPTION
Change the current working directory to the directory associated with the mark.

For example,

$ sm log

/var/log

$ gm log

$ pwd

/var/log
.SH AUTHOR
Written by Charles Pilon.
.SH FILES
~/marks
.SH SEE ALSO
am(1), cm(1), dm(1), em(1), im(1), lm(1), sm(1)
.SH COPYRIGHT
Copyright 2016 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
