.TH im 1 "13 November 2016" "markdir 1.0.0"
.SH NAME
im - is marked
.SH SYNOPSIS
.B im
.I mark
.B
.SH DESCRIPTION
Checks to see if the current working directory is tagged in the mark file. If so, the tag is output to STDOUT.
.SH AUTHOR
Written by Charles Pilon.
.SH FILES
~/marks
.SH SEE ALSO
am(1), cm(1), dm(1), em(1), gm(1), lm(1), sm(1)
.SH COPYRIGHT
Copyright 2016 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
