.TH lm 1 "17 January 2022" "markdir 2.1.0"
.SH NAME
lm - list marks
.SH SYNOPSIS
.B lm
.I [mark]
.B
.SH DESCRIPTION
Lists the directory and description for the specified mark, or all marks if no mark is specified.

For example,

$ lm
[
  {
    "mark": "log",
    "description": "Log files",
    "dir": "/var/log"
  },
  ...
]

$ lm log
{
  "dir": "/var/log",
  "description": "Log files"
}
```
.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
MARKFILE  File used to map marks to directories and directories to tasks.
.SH SEE ALSO
am(1), bd(1), cm(1), dm(1), em(1), gm(1), im(1), sm(1), td(1), xd(1)
.SH COPYRIGHT
Copyright 2022 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
