.TH sm 1 "17 January 2022" "markdir 2.1.0"
.SH NAME
sm - show mark
.SH SYNOPSIS
.B sm
.I mark
.B
.SH DESCRIPTION
Echos the directory tagged by the specified mark to STDOUT.

For example,

$ ls $(sm log)/apache2

access.log  error.log  other_vhosts_access.log
.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
MARKFILE  File used to map marks to directories and directories to tasks.
.SH SEE ALSO
am(1), bd(1), cm(1), dm(1), em(1), gm(1), im(1), lm(1), td(1), xd(1)
.SH COPYRIGHT
Copyright 2022 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
