.TH st 1 "17 February 2024" "markdir 2.2.0"
.SH NAME
st - show tasks
.SH SYNOPSIS
.B sm
.I mark
.B
.SH DESCRIPTION
Echos the task names and definitions to STDOUT.

For example,

$ gm myproject
$ st
default              poetry run start_dev
test                 poetry run pytest -W ignore::DeprecationWarning

.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
MARKFILE  File used to map marks to directories and directories to tasks.
.SH SEE ALSO
am(1), bd(1), cm(1), dm(1), em(1), gm(1), im(1), lm(1), td(1), xd(1)
.SH COPYRIGHT
Copyright 2024 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
