.TH xd 1 "17 January 2022" "markdir 2.2.0"
.SH NAME
xd - execute directory
.SH SYNOPSIS
.B xd [task]
.B
.SH DESCRIPTION
Executes the named task associated with the directory, or the run task by default.
.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
MARKFILE  File used to map marks to directories and directories to tasks.
.SH SEE ALSO
am(1), bd(1), cm(1), dm(1), em(1), gm(1), im(1), lm(1), sm(1), st(1), td(1)
.SH COPYRIGHT
Copyright 2024 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
