.TH dds 1 "30 March 2024" "sessiondir 3.0.0"
.SH NAME
ads - delete directory for session
.SH SYNOPSIS
.B dds
.I dds
.B
.SH DESCRIPTION
Delete the default directory for the session.

.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
SESSIONFILE  File used to hold sessiondir configuration.
.SH SEE ALSO
ads(1), gds(1)
.SH COPYRIGHT
Copyright 2024 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
