.TH dm 1 "30 March 2024" "markdir 3.0.0"
.SH NAME
dm - delete mark
.SH SYNOPSIS
.B dm
.I mark
.B
.SH DESCRIPTION
Deletes a mark from the mark file.

For example,
.br
$ sm log
.br
/var/log
.br
$ dm log
.br
$ sm log
.br
log not found
.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
MARKFILE  File used to map marks to directories and directories to tasks.
.SH SEE ALSO
am(1), cm(1), em(1), gm(1), im(1), lm(1), sm(1)
.SH COPYRIGHT
Copyright 2024 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
