.TH lm 1 "30 March 2024" "markdir 3.0.0"
.SH NAME
lm - list marks
.SH SYNOPSIS
.B lm
.I [mark]
.B
.SH DESCRIPTION
Lists the directory and description for the specified mark, or all marks if no mark is specified.

For example,

$ lm
.br
myproject1                          My Project                     /projects/myproject1
.br
myproject2                          My Second Project              /projects/myproject2
.br
myproject3                          My Third Project               /projects/myproject3
.br

$ lm myproject2
.br
myproject2                          My Second Project              /projects/myproject2

.SH AUTHOR
Written by Charles Pilon.
.SH ENVIRONMENT
MARKFILE  File used to map marks to directories and directories to tasks.
.SH SEE ALSO
am(1), cm(1), dm(1), em(1), gm(1), im(1), sm(1)
.SH COPYRIGHT
Copyright 2024 Charles Pilon
.SH LICENSE
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
